---
# tasks file for repos
- name: teste pacote zabbix 
  shell: "rpm -qa | grep zabbix-agent"
  register: repo


- name: baixando pacote zabbix-agent
  shell: "rpm -Uvh http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm"
  when:  repo.rc != 0 


- name: Instalando agent-zabbix
  yum:
    name: zabbix-agent
    state: installed  
  
- name: Copiando arquivo de configuracao do zabbix-agent por segurança 
  copy:
    src: /etc/zabbix/zabbix_agentd.conf
    dest: /tmp
  

- name: config zabbix-agent.conf  server 
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server=127.0.0.1'
    line: 'Server=192.168.122.245'

- name: config zabbix-agent.conf server active
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive=127.0.0.1'
    line: 'ServerActive=192.168.122.245'

- name: config zabbix-agent.conf serveractive
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Hostname=Zabbix server'
    line: 'Hostname={{hname.stdout}}'
    
- name: Iniciar agente zabbix
  service:
    name: zabbix-agent
    state: started
    enabled: yes


- name: instalando o zabbix-api
  pip:
    name: zabbix-api

- name: firewalld 
  shell: "firewall-cmd --zone=public --add-port=10050/tcp --permanent ; firewall-cmd --zone=public --add-port=10051/tcp --permanent && firewall-cmd --reload"

- name: Iniciar agente zabbix
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes        